apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cd-server-rbac-clusterrole.yaml
- cd-server-rbac-clusterrolebinding.yaml
- cd-notifications-controller-rbac-clusterrole.yaml
- cd-notifications-controller-rbac-clusterrolebinding.yaml
