####################################################################################################
# hanzocd-dev
####################################################################################################
FROM hanzocd-base
COPY hanzocd /usr/local/bin/

USER root
RUN ln -s /usr/local/bin/hanzocd /usr/local/bin/hanzocd-server && \
    ln -s /usr/local/bin/hanzocd /usr/local/bin/hanzocd-repo-server && \
    ln -s /usr/local/bin/hanzocd /usr/local/bin/hanzocd-application-controller && \
    ln -s /usr/local/bin/hanzocd /usr/local/bin/hanzocd-dex && \
    ln -s /usr/local/bin/hanzocd /usr/local/bin/hanzocd-notifications && \
    ln -s /usr/local/bin/hanzocd /usr/local/bin/hanzocd-applicationset-controller

USER 999
