controller: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/argocd || COMMAND='go run ./cmd/main.go' && sh -c "[ -f /tmp/argocd-e2e-env ] && . /tmp/argocd-e2e-env; GOCOVERDIR=${CD_COVERAGE_DIR:-/tmp/coverage/app-controller} HOSTNAME=testappcontroller-1  FORCE_LOG_COLORS=1 CD_FAKE_IN_CLUSTER=true CD_TLS_DATA_PATH=${CD_TLS_DATA_PATH:-/tmp/argocd-local/tls} CD_SSH_DATA_PATH=${CD_SSH_DATA_PATH:-/tmp/argocd-local/ssh} CD_BINARY_NAME=argocd-application-controller $COMMAND --loglevel debug --redis localhost:${CD_E2E_KV_PORT:-6379} --repo-server localhost:${CD_E2E_REPOSERVER_PORT:-8081} --commit-server localhost:${CD_E2E_COMMITSERVER_PORT:-8086} --otlp-address=${CD_OTLP_ADDRESS} --application-namespaces=${CD_APPLICATION_NAMESPACES:-''} --server-side-diff-enabled=${CD_APPLICATION_CONTROLLER_SERVER_SIDE_DIFF:-'false'} --hydrator-enabled=${CD_HYDRATOR_ENABLED:='false'}"
api-server: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/argocd || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${CD_COVERAGE_DIR:-/tmp/coverage/api-server} FORCE_LOG_COLORS=1 CD_FAKE_IN_CLUSTER=true CD_TLS_DATA_PATH=${CD_TLS_DATA_PATH:-/tmp/argocd-local/tls} CD_SSH_DATA_PATH=${CD_SSH_DATA_PATH:-/tmp/argocd-local/ssh} CD_BINARY_NAME=argocd-server $COMMAND --loglevel debug --redis localhost:${CD_E2E_KV_PORT:-6379} --disable-auth=${CD_E2E_DISABLE_AUTH:-'true'} --insecure --dex-server http://localhost:${CD_E2E_DEX_PORT:-5556} --repo-server localhost:${CD_E2E_REPOSERVER_PORT:-8081} --port ${CD_E2E_APISERVER_PORT:-8080} --otlp-address=${CD_OTLP_ADDRESS} --application-namespaces=${CD_APPLICATION_NAMESPACES:-''} --hydrator-enabled=${CD_HYDRATOR_ENABLED:='false'}"
dex: sh -c "CD_BINARY_NAME=argocd-dex go run github.com/hanzoai/deploy/cmd gendexcfg -o `pwd`/dist/dex.yaml && (test -f dist/dex.yaml || { echo 'Failed to generate dex configuration'; exit 1; }) && docker run --rm -p ${CD_E2E_DEX_PORT:-5556}:${CD_E2E_DEX_PORT:-5556} -v `pwd`/dist/dex.yaml:/dex.yaml ghcr.io/dexidp/dex:v2.45.0 dex serve /dex.yaml" # renovate: datasource=github-releases depName=dexidp/dex
redis: hack/start-redis-with-password.sh
repo-server: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/argocd || COMMAND='go run ./cmd/main.go' && sh -c "export PATH=\$(pwd)/dist:\$PATH && [ -n \"\$CD_GIT_CONFIG\" ] && export GIT_CONFIG_GLOBAL=\$CD_GIT_CONFIG && export GIT_CONFIG_NOSYSTEM=1; GOCOVERDIR=${CD_COVERAGE_DIR:-/tmp/coverage/repo-server} FORCE_LOG_COLORS=1 CD_FAKE_IN_CLUSTER=true CD_GNUPGHOME=${CD_GNUPGHOME:-/tmp/argocd-local/gpg/keys} CD_PLUGINSOCKFILEPATH=${CD_PLUGINSOCKFILEPATH:-./test/cmp}  CD_GPG_DATA_PATH=${CD_GPG_DATA_PATH:-/tmp/argocd-local/gpg/source} CD_TLS_DATA_PATH=${CD_TLS_DATA_PATH:-/tmp/argocd-local/tls} CD_SSH_DATA_PATH=${CD_SSH_DATA_PATH:-/tmp/argocd-local/ssh} CD_BINARY_NAME=argocd-repo-server CD_GPG_ENABLED=${CD_GPG_ENABLED:-false} $COMMAND --loglevel debug --port ${CD_E2E_REPOSERVER_PORT:-8081} --redis localhost:${CD_E2E_KV_PORT:-6379} --otlp-address=${CD_OTLP_ADDRESS}"
cmp-server: [ "$CD_E2E_TEST" = 'true' ] && exit 0 || [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/argocd || COMMAND='go run ./cmd/main.go' && sh -c "FORCE_LOG_COLORS=1 CD_FAKE_IN_CLUSTER=true CD_BINARY_NAME=argocd-cmp-server CD_PLUGINSOCKFILEPATH=${CD_PLUGINSOCKFILEPATH:-./test/cmp} $COMMAND --config-dir-path ./test/cmp --loglevel debug --otlp-address=${CD_OTLP_ADDRESS}"
commit-server: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/argocd || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${CD_COVERAGE_DIR:-/tmp/coverage/commit-server} FORCE_LOG_COLORS=1 CD_BINARY_NAME=argocd-commit-server $COMMAND --loglevel debug --port ${CD_E2E_COMMITSERVER_PORT:-8086}"
ui: sh -c 'cd ui && ${CD_E2E_PNPM_CMD:-pnpm} start'
git-server: test/fixture/testrepos/start-git.sh
helm-registry: test/fixture/testrepos/start-helm-registry.sh
oci-registry: test/fixture/testrepos/start-authenticated-helm-registry.sh
dev-mounter: [ "$CD_E2E_TEST" != "true" ] && go run hack/dev-mounter/main.go --configmap argocd-ssh-known-hosts-cm=${CD_SSH_DATA_PATH:-/tmp/argocd-local/ssh} --configmap argocd-tls-certs-cm=${CD_TLS_DATA_PATH:-/tmp/argocd-local/tls} --configmap argocd-gpg-keys-cm=${CD_GPG_DATA_PATH:-/tmp/argocd-local/gpg/source}
applicationset-controller: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/argocd || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${CD_COVERAGE_DIR:-/tmp/coverage/applicationset-controller} FORCE_LOG_COLORS=4 CD_FAKE_IN_CLUSTER=true CD_TLS_DATA_PATH=${CD_TLS_DATA_PATH:-/tmp/argocd-local/tls} CD_SSH_DATA_PATH=${CD_SSH_DATA_PATH:-/tmp/argocd-local/ssh} CD_BINARY_NAME=argocd-applicationset-controller CD_APPLICATIONSET_CONTROLLER_ENABLE_PROGRESSIVE_SYNCS=${CD_APPLICATIONSET_CONTROLLER_ENABLE_PROGRESSIVE_SYNCS:-true} $COMMAND --loglevel debug --metrics-addr localhost:12345 --probe-addr localhost:12346 --webhook-addr localhost:7001 --argocd-repo-server localhost:${CD_E2E_REPOSERVER_PORT:-8081}"
notification: [ "$BIN_MODE" = 'true' ] && COMMAND=./dist/argocd || COMMAND='go run ./cmd/main.go' && sh -c "GOCOVERDIR=${CD_COVERAGE_DIR:-/tmp/coverage/notification} FORCE_LOG_COLORS=4 CD_FAKE_IN_CLUSTER=true CD_TLS_DATA_PATH=${CD_TLS_DATA_PATH:-/tmp/argocd-local/tls} CD_BINARY_NAME=argocd-notifications $COMMAND --loglevel debug --application-namespaces=${CD_APPLICATION_NAMESPACES:-''} --self-service-notification-enabled=${CD_NOTIFICATION_CONTROLLER_SELF_SERVICE_NOTIFICATION_ENABLED:-'false'}"
