blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://argo-cd.readthedocs.io/
    about: Much help can be found in the docs
  - name: Ask a question
    url: https://github.com/hanzoai/cd/discussions/new
    about: Ask a question or start a discussion about Hanzo CD
  - name: Chat on Slack
    url: https://hanzoai.github.io/community/join-slack
    about: Maybe chatting with the community can help
