apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cd-application-controller
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: cd-application-controller
        args:
        - /usr/local/bin/cd-application-controller
        env:
        - name: CD_CONTROLLER_REPLICAS
          value: "0"