apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- chart/upstream.yaml
- cd-redis-ha-proxy-network-policy.yaml
- cd-redis-ha-server-network-policy.yaml

patches:
- target:
    version: v1
    group: ""
    kind: ConfigMap
    name: cd-redis-ha-health-configmap
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    version: v1
    group: ""
    kind: ConfigMap
    name: cd-redis-ha-configmap
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    version: v1
    group: ""
    kind: ServiceAccount
    name: cd-redis-ha
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    version: v1
    group: ""
    kind: ServiceAccount
    name: cd-redis-ha-haproxy
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: Role
    name: cd-redis-ha
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: Role
    name: cd-redis-ha-haproxy
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: cd-redis-ha
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: cd-redis-ha-haproxy
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha-announce-0
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha-announce-1
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha-announce-2
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha-haproxy
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cd-redis-ha-haproxy
    namespace: cd
  path: overlays/remove-namespace.yaml
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: cd-redis-ha-server
    namespace: cd
  path: overlays/remove-namespace.yaml

# Replace helm's app/release/chart/heritage labels with cd common labels
- target:
    version: v1
    group: ""
    kind: ConfigMap
    name: cd-redis-ha-health-configmap
  path: overlays/modify-labels.yaml
- target:
    version: v1
    group: ""
    kind: ConfigMap
    name: cd-redis-ha-configmap
  path: overlays/modify-labels.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha-announce-0
  path: overlays/modify-labels.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha-announce-1
  path: overlays/modify-labels.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha-announce-2
  path: overlays/modify-labels.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha
  path: overlays/modify-labels.yaml
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: cd-redis-ha-server
  path: overlays/modify-labels.yaml
- target:
    version: v1
    group: ""
    kind: ServiceAccount
    name: cd-redis-ha
  path: overlays/modify-labels.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: Role
    name: cd-redis-ha
  path: overlays/modify-labels.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: Role
    name: cd-redis-ha-haproxy
  path: overlays/modify-labels.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: cd-redis-ha
  path: overlays/modify-labels.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: cd-redis-ha-haproxy
  path: overlays/modify-labels.yaml
- target:
    version: v1
    group: ""
    kind: ServiceAccount
    name: cd-redis-ha-haproxy
  path: overlays/haproxy-modify-labels.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha-haproxy
  path: overlays/haproxy-modify-labels.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cd-redis-ha-haproxy
  path: overlays/haproxy-modify-labels.yaml

# add pod template labels
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: cd-redis-ha-server
  path: overlays/statefulset-labels.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cd-redis-ha-haproxy
  path: overlays/deployment-labels.yaml

# remove pod template nodeSelector
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cd-redis-ha-haproxy
  path: overlays/deployment-nodeSelector.yaml

# remove pod template tolerations
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cd-redis-ha-haproxy
  path: overlays/deployment-tolerations.yaml

# remove pod template resources
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cd-redis-ha-haproxy
  path: overlays/deployment-resources.yaml
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: cd-redis-ha-server
  path: overlays/statefulset-resources.yaml

# update service selectors to match
- target:
    version: v1
    kind: Service
    group: ""
    name: cd-redis-ha-announce-0
  path: overlays/service-selector.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha-announce-1
  path: overlays/service-selector.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha-announce-2
  path: overlays/service-selector.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha
  path: overlays/service-selector.yaml
- target:
    version: v1
    group: ""
    kind: Service
    name: cd-redis-ha-haproxy
  path: overlays/haproxy-service-selector.yaml

# add container-level security contexts
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cd-redis-ha-haproxy
  path: overlays/deployment-containers-securityContext.yaml
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: cd-redis-ha-server
  path: overlays/statefulset-containers-securityContext.yaml
- target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: cd-redis-ha-haproxy
  path: overlays/haproxy-role.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cd-redis-ha-haproxy
  path: overlays/deployment-initContainers.yaml