---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-server
spec:
  template:
    spec:
      containers:
      - name: cd-server
        volumeMounts:
        - name: known-hosts
          mountPath: /etc/ssh/ssh_known_hosts
          subPath: known_hosts
      volumes:
      - name: known-hosts
        configMap:
          name: cd-known-hosts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-repo-server
spec:
  template:
    spec:
      containers:
      - name: cd-repo-server
        volumeMounts:
        - name: known-hosts
          mountPath: /etc/ssh/ssh_known_hosts
          subPath: known_hosts
      volumes:
      - name: known-hosts
        configMap:
          name: cd-known-hosts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-application-controller
spec:
  template:
    spec:
      containers:
      - name: cd-application-controller
        volumeMounts:
        - name: known-hosts
          mountPath: /etc/ssh/ssh_known_hosts
          subPath: known_hosts
      volumes:
      - name: known-hosts
        configMap:
          name: cd-known-hosts
