apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-ui
spec:
  selector:
    matchLabels:
      app: cd-ui
  template:
    metadata:
      labels:
        app: cd-ui
    spec:
      containers:
        - name: cd-ui
          image: cd-ui
          env:
            - name: CD_API_URL
              value: https://cd-server
            - name: CD_E2E_JS_HOST
              value: "0.0.0.0"
          ports:
            - containerPort: 4000
              name: http
