# This example demonstrates the combining of the git generator with a cluster generator
# The expected output would be an application per git directory and a cluster (application_count = git directory * clusters)
#
#
apiVersion: apps.hanzo.ai/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
spec:
  generators:
  - matrix:
      generators:
        - git:
            repoURL: https://github.com/hanzoai/cd.git
            revision: HEAD
            directories:
            - path: applicationset/examples/matrix/cluster-addons/*
        - clusters:
            selector:
              matchLabels:
                apps.hanzo.ai/secret-type: cluster
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
    spec:
      project: '{{metadata.labels.environment}}'
      source:
        repoURL: https://github.com/hanzoai/cd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{path.basename}}'
