apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patches:
- path: overlays/hanzocd-repo-server-deployment.yaml
- path: overlays/hanzocd-server-deployment.yaml
- path: overlays/hanzocd-application-controller-statefulset.yaml
- path: overlays/hanzocd-cmd-params-cm.yaml


images:
- name: quay.io/argoproj/argocd
  newName: ghcr.io/hanzoai/deploy
  newTag: latest
resources:
- ../../base/application-controller
- ../../base/applicationset-controller
- ../../base/dex
- ../../base/repo-server
- ../../base/server
- ../../base/config
- ../../base/notification
- ./redis-ha
