apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patches:
- path: overlays/cd-repo-server-deployment.yaml
- path: overlays/cd-server-deployment.yaml
- path: overlays/cd-application-controller-statefulset.yaml
- path: overlays/cd-cmd-params-cm.yaml


images:
- name: ghcr.io/hanzoai/cd
  newName: ghcr.io/hanzoai/cd
  newTag: latest
resources:
- ../../base/application-controller
- ../../base/applicationset-controller
- ../../base/dex
- ../../base/repo-server
- ../../base/server
- ../../base/config
- ../../base/notification
- ./redis-ha
